# Generated by Django 5.2 on 2025-06-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacao', '0002_alter_locacao_valor_total_previsto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Dinheiro', 'Dinheiro')], max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_hora_pagamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacao.locacao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_hora_pagamento'],
            },
        ),
    ]
