# Generated by Django 5.2.1 on 2025-06-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_cliente_cidade'),
        ('seguro', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_retirada', models.DateTimeField()),
                ('data_hora_prevista_devolucao', models.DateTimeField()),
                ('data_hora_efetiva_devolucao', models.DateTimeField(blank=True, null=True)),
                ('valor_total_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguro.seguro')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
                'ordering': ['-data_hora_retirada'],
            },
        ),
    ]
